"""create trusted_sources table

Revision ID: 04c715c6607b
Revises: 8fc6960a9b68
Create Date: 2026-08-18 13:48:40.756327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c715c6607b'
down_revision = '8fc6960a9b68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('trusted_sources',
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('source_id')
        )
        op.create_index(op.f('ix_trusted_sources_source_id'), 'trusted_sources', ['source_id'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_trusted_sources_source_id'), table_name='trusted_sources')
        op.drop_table('trusted_sources')
    except Exception:
        pass
    # ### end Alembic commands ###
