"""add_onboarding_and_financial_features

Revision ID: 55acbe893a8f
Revises: a2a876b621b0
Create Date: 2026-08-18 05:28:45.391557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55acbe893a8f'
down_revision = 'a2a876b621b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financing_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('requested_term', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_financing_requests_request_id'), 'financing_requests', ['request_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.add_column('agents', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('region', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('agent_type', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'agent_type')
    op.drop_column('agents', 'region')
    op.drop_column('agents', 'phone')
    op.drop_column('agents', 'business_name')
    op.drop_column('agents', 'full_name')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_financing_requests_request_id'), table_name='financing_requests')
    op.drop_table('financing_requests')
    # ### end Alembic commands ###
