"""Initial schema

Revision ID: a2a876b621b0
Revises: None
Create Date: 2026-08-17 15:16:18.245898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a876b621b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('business_age', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=True),
    sa.Column('float_balance', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('consent_status', sa.Boolean(), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('profile_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_table('agent_daily_metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=True),
    sa.Column('avg_cash_balance', sa.Float(), nullable=True),
    sa.Column('avg_float_balance', sa.Float(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_agent_daily_metrics_date'), 'agent_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_agent_daily_metrics_metric_id'), 'agent_daily_metrics', ['metric_id'], unique=False)
    op.create_table('credit_assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('repayment_probability', sa.Float(), nullable=False),
    sa.Column('default_probability', sa.Float(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('indicative_credit_capacity', sa.Float(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_credit_assessments_assessment_id'), 'credit_assessments', ['assessment_id'], unique=False)
    op.create_table('customer_financial_profiles',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('activity_days', sa.Integer(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('transaction_volume', sa.Float(), nullable=True),
    sa.Column('average_transaction_value', sa.Float(), nullable=True),
    sa.Column('median_transaction_value', sa.Float(), nullable=True),
    sa.Column('monthly_inflows', sa.Float(), nullable=True),
    sa.Column('monthly_outflows', sa.Float(), nullable=True),
    sa.Column('inflow_outflow_ratio', sa.Float(), nullable=True),
    sa.Column('cashflow_volatility', sa.Float(), nullable=True),
    sa.Column('transaction_consistency', sa.Float(), nullable=True),
    sa.Column('savings_behavior_score', sa.Float(), nullable=True),
    sa.Column('activity_growth_rate', sa.Float(), nullable=True),
    sa.Column('financial_history_months', sa.Float(), nullable=True),
    sa.Column('repayment_history_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_transaction_volume', sa.Float(), nullable=False),
    sa.Column('predicted_float_demand', sa.Float(), nullable=False),
    sa.Column('predicted_cash_demand', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_id'), 'forecasts', ['forecast_id'], unique=False)
    op.create_table('loans',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('repayment_status', sa.String(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('default_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_index(op.f('ix_loans_loan_id'), 'loans', ['loan_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_amount', sa.Float(), nullable=True),
    sa.Column('recommended_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('float_balance', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_id'), 'anomalies', ['anomaly_id'], unique=False)
    op.create_table('credit_explanations',
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('importance_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['credit_assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    op.create_index(op.f('ix_credit_explanations_explanation_id'), 'credit_explanations', ['explanation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_explanations_explanation_id'), table_name='credit_explanations')
    op.drop_table('credit_explanations')
    op.drop_index(op.f('ix_anomalies_anomaly_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_loans_loan_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_forecasts_forecast_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('customer_financial_profiles')
    op.drop_index(op.f('ix_credit_assessments_assessment_id'), table_name='credit_assessments')
    op.drop_table('credit_assessments')
    op.drop_index(op.f('ix_agent_daily_metrics_metric_id'), table_name='agent_daily_metrics')
    op.drop_index(op.f('ix_agent_daily_metrics_date'), table_name='agent_daily_metrics')
    op.drop_table('agent_daily_metrics')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
