"""create referrals table

Revision ID: d20af016f6ff
Revises: 04c715c6607b
Create Date: 2026-08-18 17:11:23.412856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20af016f6ff'
down_revision = '04c715c6607b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('referrals',
        sa.Column('referral_id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('institution_id', sa.Integer(), nullable=False),
        sa.Column('requested_amount', sa.Float(), nullable=False),
        sa.Column('purpose', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('consent_status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('consent_requested_at', sa.DateTime(), nullable=True),
        sa.Column('consent_responded_at', sa.DateTime(), nullable=True),
        sa.Column('consent_expiry', sa.DateTime(), nullable=True),
        sa.Column('application_status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
        sa.ForeignKeyConstraint(['institution_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('referral_id')
        )
        op.create_index(op.f('ix_referrals_referral_id'), 'referrals', ['referral_id'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_referrals_referral_id'), table_name='referrals')
        op.drop_table('referrals')
    except Exception:
        pass
    # ### end Alembic commands ###
